# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3388608143447be425a1e860eae18d7f173eebd28b49a088524dd9491eb49a4cadd52538e04237d9843d401f23504e412e8cb79b2594efa22c886e1d5733b4b

test:
  secret_key_base: 14dd3224a36d960d738ae9c535a2f8331565b9ba09f82d90ce4e279ae913a471c85bab1aef16e4ffc4c1c69ae31221c08dfc39bab843e0c748a4b5a136a6d38b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
